name: Debug
on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main, traiman/ci-squashed]

jobs:
  doDebug:
    if: |
      (github.event_name == 'issue_comment' && github.event.issue.pull_request && github.event.comment.body == 'rebuild!') ||
      (github.event_name == 'pull_request') ||
      (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-22.04
    #services:
    #  mongo:
    #    image: mongo:4.0
    #    env:
    #      MONGO_INITDB_ROOT_USERNAME: root
    #      MONGO_INITDB_ROOT_PASSWORD: password
      # Temporarily disable due to bug on gasp when running more than one service container...
      # cognito:
      #   image: jagregory/cognito-local:3.21.1
      #   env:
      #     PORT: 5000
    steps:
      - name: date
        id: date
        run:  echo "NOW=`date --iso-8601=seconds`" | tee $GITHUB_OUTPUT
      - run: whoami
      - run: jq -C -n env
      - name: toJSON(github)
        run: |
            cat << 'EOF' | jq -C .
            ${{ toJSON(github) }}
            EOF
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: PrintEventData.yaml
          inputs: '{ "inputA": "value" }'


      