name: Debug
on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main, traiman/ci-squashed]

jobs:
  doDebug:
    if: |
      (github.event_name == 'issue_comment' && github.event.issue.pull_request && github.event.comment.body == 'rebuild!') ||
      (github.event_name == 'pull_request') ||
      (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-22.04
    services:
      mongo:
        image: mongo:4.0
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
      # Temporarily disable due to bug on gasp when running more than one service container...
      # cognito:
      #   image: jagregory/cognito-local:3.21.1
      #   env:
      #     PORT: 5000
    steps:
      - name: date
        id: date
        run:  echo "NOW=`date --iso-8601=seconds`" | tee $GITHUB_OUTPUT
      - run: whoami
      - run: jq -C -n env
      - name: toJSON(github)
        run: |
            cat << 'EOF' | jq -C .
            ${{ toJSON(github) }}
            EOF
      - uses: actions/checkout@v2
      - run: rm -rf $GITHUB_EVENT_PATH
      - name: client - Process Test Results
        uses: im-open/process-jest-test-results@v2.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-file: .github/workflows/jest-results.json
          report-name: Client Jest Test Results
          ignore-test-failures: false
          create-status-check: true
          create-pr-comment: true
          update-comment-if-one-exists: false
          timezone:	UTC
