name: PrintEventData

on:
  push:
  merge_group:
    types:
      - checks_requested
      - destroyed
    branches:
      - main
  pull_request:
  workflow_dispatch:
  check_run:
    types: [created,requested_action, rerequested, completed]
jobs:    
  doPrintEventData:
    runs-on: ubuntu-22.04    
    timeout-minutes: 15
    name: ${{github.event_name}}
    steps:
      - name: date
        id: date
        run:  echo "NOW=`date --iso-8601=seconds`" | tee $GITHUB_OUTPUT
      - run: env | sort
      - name: toJSON(github)
        run: |
            cat << 'EOF' | jq -C .
            ${{ toJSON(github) }}
            EOF
      - name: Create Tag
        uses: opensafety/action-create-tag@main
        with:
          token: ${{ github.token }}
          tag-name: ${{ github.repository }}/actions/runs/${{ github.run_id }}
          tag-message: |
            Repo updated: ${{ github.event.repository.updated_at }}
            Now:          ${{ steps.date.output.NOW }}
            Event:        ${{ github.event_name }}
            Workflow:     ${{ github.workflow }}
            Ref:          ${{ github.ref }}
            Run URL:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

